version: "3"

services:

  constructor:
    # build: .
    image: constructor
    depends_on:
      - postgres
      - isfront
      - redis
    environment:
      - DB_HOST=0.0.0.0
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379
#    volumes:
#      - ./src:/src
#      - ./tests:/tests
    command: python main.py
    network_mode: host
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  isfront:
    image: constructor
    ports:
      - "8081:8081"
    command: python isfront.py
