"""Initial

Revision ID: baff62ba4030
Revises: 
Create Date: 2023-02-02 22:18:07.483492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baff62ba4030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outer_id', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('current_scenario_name', sa.String(), nullable=True),
    sa.Column('current_node_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outer_id')
    )
    op.create_table('out_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.outer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('scenario_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('ctx', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.outer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('template_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scenario'], ['scenarios.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_texts')
    op.drop_table('user_contexts')
    op.drop_table('scenarios')
    op.drop_table('out_messages')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
